repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-yaml
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: debug-statements

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      language_version: python3.10.4
      args: [--line-length=120]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [--max-line-length=120]

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: [--profile black --line-length 120]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.960
  hooks:
    - id: mypy
      additional_dependencies: [types-requests]
