name: Codecov-check

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Run tests and collect coverage
      run: poetry run python -m pytest --cov .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
