# This workflow will upload a Python Package using Poetry when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install poetry
      uses: snok/install-poetry@v1.3.3
      with:
        version: 1.2.0b2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
#        cache: 'poetry' # skip cache when publishing

    - name: Install dependencies
      run: poetry install --no-root

    - name: Install poetry plugins
      run: |
        poetry self add poetry-dynamic-versioning-plugin@0.3.2

    - name: Build
      id: build
      run: |
        poetry build

    - name: Publish
      if: steps.build.outcome == 'success'
      run: |
        poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
